### ISSUE TITLE
$100 - Downward/upward slope fix for FlxTilemapExt

### ISSUE THREAD

**Issue by chosencharacters** [chosencharacters/squidBounties#2]
Problem: FlxTilemapExt has upward slopes and downward slopes. When going up slopes you are glued to the slope so you can smoothly and happily go upwards except for certain speeds where you hit "snags". When going down a slope you do *not* glue to the slope at all :(

A sane person would switch to Nape or Echo or some new physics engine, but for us poor souls who've been working on games that rely on out of box physics, well, it's a bad time.

To claim this bounty demonstrate a fix where a player:
1. Goes up the slope while glued to the slope while not snagging (getting stuck on the tile)
2. Down the slope while glued to the slope
3. Without relying on Nape or an entirely new physics engine, just default HaxeFlixel.

Optimally this is a rewrite or a modification of FlxTilemapExt

You can find the base project here:

https://github.com/chosencharacters/SlopeLand

Happy hunting!

**Comment by jinjinjinK** [comment]
I'm claiming this one. In fact, I already have it working on the FlxTilemapExt demo.
I'm going to build SlopeLand and see if it works as intended too.
