### ISSUE TITLE
$50 - Ogmo 2 -> Ogmo 3 Convertor

### ISSUE THREAD

**Issue by chosencharacters** [chosencharacters/squidBounties#3]
Ogmo 3 is the newest version of Ogmo with a diverse feature set and overall great additional layer of polish that Ogmo 2 lacks. However, I (and many others) lack the ability to move to Ogmo 3 from our Ogmo 2 projects due to their similar but different ways of reading file formats specifically.

Therefore, I'm opening a bounty for a simple Ogmo 2 -> Ogmo 3 converter that takes Ogmo 2 files (.xml) and outputs Ogmo 3 files (.json)

This does not require a working knowledge of Haxe, Flixel, or anything, but it does require a knowledge of XML and JSON formats as well as familiarity with Ogmo. I have a WIP Python file that can be looked at for reference if need be, I went decently far but mine was a Renaine-specific solution so it's not general enough.

To claim this bounty you'll have to be able to take a Renaine Ogmo 2 file, and an analogous Renaine file written in Ogmo 3, and pass a diff check where there are no differences between the expected result and actual result. This tool should work on entire directories, optimally cloning a directory and replacing every .oel with a .ogmo file.

**Comment by TheSpydog** [comment]
I'll work on this over the weekend!

**Comment by Aurel300** [comment]
@chosencharacters Could you please post an XML/JSON example? Maybe also the Python script?
