### ISSUE TITLE
$50 - Ogmo 3 Take Picture of Level

### ISSUE THREAD

**Issue by chosencharacters** [chosencharacters/squidBounties#4]
Part of my move to Ogmo 3 with Renaine will require the implementation of one key missing feature -taking a picture of the level, which was available in Ogmo 2. Simply put, when the button was clicked in Ogmo 2 it would immediately take all visible layers and print them to a .png with the option of where to save as.

This task will involve
- Reading the level's tiles
- Reading the level's entities + their sprites
- Writing them to a .png
- Saving that in a location
- Adding it to Ogmo 3 UI (this does not need to be interactive beyond just a button to do it with all visible layers, just like Ogmo 2, and a save area selection box)

To claim this bounty it'll have to be accepted as a PR into Ogmo 3 which can be found at https://github.com/Ogmo-Editor-3/OgmoEditor3-CE

**Comment by TheSpydog** [comment]
I'll work on this over the weekend!

**Comment by TheSpydog** [comment]
What exactly do you mean by a "save area selection box"?

**Comment by chosencharacters** [comment]
Ah yea I just meant a file explorer to select save location

**Comment by TheSpydog** [comment]
This has turned out to be more complicated than I originally thought and I don't know when I'll have time to work on this, so I'm going to un-claim this bounty and let someone else take a crack at it!

**Comment by Ohmnivore** [comment]
https://github.com/Ogmo-Editor-3/OgmoEditor3-CE/pull/136 PR accepted :)
