### ISSUE TITLE
$600 - Inventory And Others

### ISSUE THREAD

**Issue by xhunterko** [chosencharacters/squidBounties#8]
Hey there! I was wondering if someone were to help me with the following in my game:

-Inventory System
-Other Bugs And Features
-Some Open Source Projects

If you are interested then please get back with me.

**Comment by tobil4sk** [comment]
Willing to help you out with this!

**Comment by xhunterko** [comment]
Alrighty, looking forward to working with you!

**Comment by tobil4sk** [comment]
Thanks, I enjoyed working on this!
